name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Methods
        run: |
          make test_with_env
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint App
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
